comment feature added
Vanchey359/java-explore-with-me pull request #5
Opened 2023-07-05 15:45 UTC by Vanchey359

2023-07-07 10:49 UTC, kalitva requested changes

2023-07-07 10:49 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/ewmService/controller/comment/AdminCommentController.java
> +    public ResponseEntity<Void> deleteCommentByAdmin(@PathVariable("commentId") Long commentId) {
Из название складывается ощущение, что здесь удаляются все комменты, оставленные админом, подумай как лучше назвать метод

2023-07-07 10:49 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/ewmService/controller/comment/PublicCommentController.java
> +    public ResponseEntity<List<CommentDto>> getCommentsByFilters(
`getCommentsByFilters --> getComments`

2023-07-07 10:49 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/ewmService/dto/comment/CommentDto.java
> +import static ru.practicum.ewmService.util.Util.YYYY_MM_DD_HH_MM_SS;
Лучше не использовать статические импорты, если класс не тестовый, это часто затрудняет чтение

2023-07-07 10:49 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/ewmService/repository/comment/CommentRepository.java
> +    List<Comment> getCommentsByFilters(@Param("text") String text,
`getCommentsByFilters --> getFilteredComments`

2023-07-07 10:49 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/ewmService/service/comment/CommentService.java
> +    CommentDto findCommentById(Long idComment);
Давай назовем правильно по английски
`idComment --> commentId`

2023-07-07 10:49 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/ewmService/service/comment/CommentService.java
> +    CommentDto updateCommentByUser(Long userId, Long eventId, Long commentId, NewCommentDto commentDto);
Многовато параметров, мы можем избавиться от `commentId` получая его из `commentDto`

2023-07-07 10:49 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/ewmService/service/comment/CommentService.java
> +    List<CommentDto> getCommentForEventById(Long idEvent, Integer from, Integer size);
Сделай объект `Pageable` в контроллере и принимай его в сервисе вместо `from` и `size`

2023-07-07 10:49 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/ewmService/service/comment/CommentService.java
> +    List<CommentDto> getCommentsByFilters(String text, Long idEvent, Long idUser, Integer from, Integer size);
Один из способов уменьшить количество параметров метода - https://www.baeldung.com/java-best-practices-many-parameters-method

2023-07-08 10:48 UTC, Vanchey359 commented on ewm-service/src/main/java/ru/practicum/ewmService/service/comment/CommentService.java
> +    CommentDto updateCommentByUser(Long userId, Long eventId, Long commentId, NewCommentDto commentDto);
Можем, но commentId нужна - она используется в контролере @PatchMapping("{commentId}")

2023-07-08 16:41 UTC, kalitva approved these changes

2023-07-08 16:41 UTC, kalitva commented on ewm-service/src/main/java/ru/practicum/ewmService/service/comment/CommentService.java
> +    CommentDto updateCommentByUser(Long userId, Long eventId, Long commentId, NewCommentDto commentDto);
Я имел ввиду  получить в контроллере и засетить в дто перед передачей в сервис 
```java
commmentDto.setId(commentId);
commentService,updateCommecnt(userId, eventId, commecntDto);
```

2023-07-08 16:45 UTC, kalitva commented
Как получилось, что есть конфликт с основной веткой? Напиши если не знаешь как разрешить

2023-07-09 10:27 UTC, merged